Verbitim lemmatizer
MAIF/melusine pull request #128
Opened 2022-02-16 17:20 UTC by adam-benjellounSG

# PR related to https://github.com/MAIF/melusine/issues/127#issue-1138862604

Adding Lemmatizer object which wraps Spacy and Lefff lemmatizers.
Fully compatible with TransformerScheduler as well as sklearn pipelines.
Enables the user to provide name of input and output columns.

Test plan (required)

```
from melusine.nlp_tools.lemmatizer import Lemmatizer

spacy_lemma_sm = Lemmatizer('clean_body', 'lemma_spacy_sm', engine='spacy', engine_conf='fr_core_news_sm')
spacy_lemma_sm.fit_transform(df_email)
```

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Implementation of wrapping around spacy and lefff lemmatizers compatible with TransformerScheduler architecture. The Lemmatizer object is compatible with sklearn pipelines and is built around an sklearn Transformer.

## Type of change

Please delete options that are not relevant.

- [X ] New feature (non-breaking change which adds functionality or feature that would cause existing functionality to not work as expected)
- [ X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
conda create -n melusine-verbitim python=3.6
conda activate melusine-verbitim
pip install melusine[lemmatizer]

- [ ] Create a Lemmatizer object of each engine
```
from melusine.nlp_tools.lemmatizer import Lemmatizer
spacy_lemma_sm = Lemmatizer('clean_body', 'lemma_spacy_sm', engine='spacy', engine_conf='fr_core_news_sm')
lefff_lemma = Lemmatizer('clean_body', 'lemma_lefff', engine='Lefff', engine_conf='fr_core_news_sm')
```
- [ ] Insert Lemmatizer object in a pipeline with TransformerScheduler objects
```
from sklearn.pipeline import Pipeline
from melusine.utils.transformer_scheduler import TransformerScheduler
from melusine.prepare_email.manage_transfer_reply import check_mail_begin_by_transfer, update_info_for_transfer_mail, add_boolean_transfer, add_boolean_answer
from melusine.prepare_email.build_historic import build_historic
from melusine.prepare_email.mail_segmenting import structure_email
from melusine.prepare_email.body_header_extraction import extract_last_body
from melusine.prepare_email.cleaning import clean_body

ManageTransferReply = TransformerScheduler(
functions_scheduler=[
    (check_mail_begin_by_transfer, None, ['is_begin_by_transfer']),
    (update_info_for_transfer_mail, None, None),
    (add_boolean_answer, None, ['is_answer']),
    (add_boolean_transfer, None, ['is_transfer'])
])

EmailSegmenting = TransformerScheduler(
functions_scheduler=[
    (build_historic, None, ['structured_historic']),
    (structure_email, None, ['structured_body'])
])

Cleaning = TransformerScheduler(
functions_scheduler=[
    (extract_last_body, None, ['last_body']),
    (clean_body, None, ['clean_body'])
])

from melusine.nlp_tools.lemmatizer import Lemmatizer

spacy_lemma_sm = Lemmatizer('clean_body', 'lemma_spacy_sm', engine='spacy', engine_conf='fr_core_news_sm')
lefff_lemma = Lemmatizer('clean_body', 'lemma_lefff', engine='Lefff', engine_conf='fr_core_news_sm')

prepare_data_pipeline = Pipeline([
  ('ManageTransferReply', ManageTransferReply),
  ('EmailSegmenting', EmailSegmenting),
  ('Cleaning', Cleaning),
  ('spacy_lemma_sm', spacy_lemma_sm),
  ('lefff_lemma', lefff_lemma)
])

df_email = prepare_data_pipeline.fit_transform(df_email)
```

**Test Configuration**:
* OS:Windows 10
* Python version:3.6.13
* Melusine version: 2.3.2

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-17 15:18 UTC, TFA-MAIF requested changes
Review done by Hugo, Charles and Tiphaine

2022-02-17 15:18 UTC, TFA-MAIF commented on melusine/nlp_tools/lemmatizer.py
> +def create_melt_tagger(nlp, name):
Hello, could you add docstring to understand what the following functions do?
Best,

2022-02-17 15:18 UTC, TFA-MAIF commented on melusine/nlp_tools/lemmatizer.py
> +        :param in_col:  input column of dataframe.
Could you use numpy format for docstring? here is the link: https://numpydoc.readthedocs.io/en/latest/format.html

2022-02-17 15:18 UTC, TFA-MAIF commented on melusine/nlp_tools/lemmatizer.py
> +        self.logger = logging.getLogger(__name__)
We do not recommand adding logger into the object but preferably at a module level.

2022-02-17 15:18 UTC, TFA-MAIF commented on melusine/utils/verbitim_transformer.py
> +
Could you add docstring?

2022-02-17 15:18 UTC, TFA-MAIF commented on melusine/nlp_tools/lemmatizer.py
> +def create_melt_tagger(nlp, name):
+ type hinting for every function with format compatible for Python <3.9

def ma_fonction(malist: List[int], mastring: str) -> Union[List, str]:

2022-02-24 09:31 UTC, adam-benjellounSG commented
Hello, 
We performed changes, please let us know if there are any points we may have missed.
Best Regards,
Adam

2022-02-28 09:18 UTC, TFA-MAIF approved these changes

2022-02-28 09:18 UTC, merged